import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { ThemeService } from '../../core/services/theme.service';

interface Author { _id:string; name:string; bio?:string; image?:string; birthDate?:string; deathDate?:string; nationality?:string; booksCount?:number; }
@Component({
 selector:'app-authors',standalone:true,imports:[CommonModule,RouterLink],
 template:`<section class="authors-page" [class.dark]="theme.isDarkMode()" dir="rtl"><div class="authors-hero"><span>مكتبة الحكمة</span><h1>المؤلفون</h1><p>تعرف على أصحاب الكتب وسيرهم وأعمالهم.</p></div><div class="authors-grid" *ngIf="!loading;else wait"><a class="author-card" *ngFor="let a of authors" [routerLink]="['/authors',a._id]"><div class="portrait"><img *ngIf="a.image" [src]="imageUrl(a.image)" [alt]="a.name"><span *ngIf="!a.image">{{initial(a.name)}}</span></div><div class="author-info"><h2>{{a.name}}</h2><p>{{a.bio || 'كاتب ومؤلف ضمن مكتبة الحكمة.'}}</p><div class="meta"><span>{{a.booksCount || 0}} كتاب</span><span *ngIf="a.nationality">{{a.nationality}}</span></div></div><span class="arrow">←</span></a></div><ng-template #wait><div class="state">جارٍ تحميل المؤلفين...</div></ng-template><div class="state error" *ngIf="error">{{error}}</div></section>`,
 styles:[`.authors-page{min-height:calc(100vh - 80px);padding:70px clamp(20px,5vw,80px);background:var(--bg-primary,#f7f7f4);color:var(--text-primary,#191919)}.authors-page.dark{background:#0b0d11;color:#f4f5f7}.authors-hero,.authors-grid{max-width:1100px;margin:auto}.authors-hero{margin-bottom:40px}.authors-hero span{font-size:12px;letter-spacing:2px;opacity:.55}.authors-hero h1{font-size:clamp(38px,6vw,70px);margin:8px 0}.authors-hero p{font-size:18px;opacity:.65}.authors-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:18px}.author-card{display:flex;gap:18px;align-items:center;padding:22px;border:1px solid rgba(127,127,127,.18);border-radius:24px;color:inherit;text-decoration:none;background:rgba(255,255,255,.72);transition:.2s}.dark .author-card{background:#14171d}.author-card:hover{transform:translateY(-5px)}.portrait{width:88px;height:88px;border-radius:50%;overflow:hidden;background:#20242b;color:white;display:grid;place-items:center;font-size:30px;flex:none}.portrait img{width:100%;height:100%;object-fit:cover}.author-info{min-width:0}.author-info h2{margin:0 0 7px}.author-info p{margin:0 0 10px;opacity:.62;line-height:1.6;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.meta{display:flex;gap:12px;font-size:12px;opacity:.65}.arrow{margin-right:auto;opacity:.45;font-size:22px}.state{text-align:center;padding:50px;opacity:.7}.error{color:#c33}`]
})
export class AuthorsComponent{private http=inject(HttpClient);public theme=inject(ThemeService);authors:Author[]=[];loading=true;error='';constructor(){this.http.get<Author[]>('http://localhost:5000/api/authors').subscribe({next:v=>{this.authors=v;this.loading=false},error:()=>{this.error='تعذر تحميل المؤلفين.';this.loading=false}})}imageUrl(v:string){return /^https?:\/\//i.test(v)?v:`http://localhost:5000${v.startsWith('/')?v:`/${v}`}`}initial(n:string){return n?.trim()?.charAt(0)||'م'}}
